function createplot(X1, Y1)
%CREATEPLOT(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 10-May-2019 18:25:46

% Create plot
plot(X1,Y1,'DisplayName','? = 0.7','Marker','diamond','LineWidth',1.25);

